"use strict"
let Indicators = require('./lib');
Object.keys(Indicators).forEach(function(indicator) {
  global[indicator] = Indicators[indicator];
})
global.AvailableIndicators = [];
global.AvailableIndicators.push('sma');
global.AvailableIndicators.push('ema');
global.AvailableIndicators.push('wma');
global.AvailableIndicators.push('wema');
global.AvailableIndicators.push('macd');
global.AvailableIndicators.push('rsi');
global.AvailableIndicators.push('bollingerbands');
global.AvailableIndicators.push('adx');
global.AvailableIndicators.push('atr');
global.AvailableIndicators.push('truerange');
global.AvailableIndicators.push('roc');
global.AvailableIndicators.push('kst');
global.AvailableIndicators.push('stochastic');
global.AvailableIndicators.push('williamsr');
global.AvailableIndicators.push('adl');
global.AvailableIndicators.push('obv');
global.AvailableIndicators.push('trix');
global.AvailableIndicators.push('averagegain');
global.AvailableIndicators.push('averageloss');
global.AvailableIndicators.push('sd');
global.AvailableIndicators.push('bullish');
global.AvailableIndicators.push('bearish');
global.AvailableIndicators.push('abandonedbaby');
global.AvailableIndicators.push('doji');
global.AvailableIndicators.push('bearishengulfingpattern');
global.AvailableIndicators.push('bullishengulfingpattern');
global.AvailableIndicators.push('darkcloudcover');
global.AvailableIndicators.push('downsidetasukigap');
global.AvailableIndicators.push('dragonflydoji');
global.AvailableIndicators.push('gravestonedoji');
global.AvailableIndicators.push('bullishharami');
global.AvailableIndicators.push('bearishharami');
global.AvailableIndicators.push('bullishharamicross');
global.AvailableIndicators.push('bearishharamicross');
global.AvailableIndicators.push('eveningdojistar');
global.AvailableIndicators.push('eveningstar');
global.AvailableIndicators.push('morningdojistar');
global.AvailableIndicators.push('morningstar');
global.AvailableIndicators.push('bullishmarubozu');
global.AvailableIndicators.push('bearishmarubozu');
global.AvailableIndicators.push('piercingline');
global.AvailableIndicators.push('bullishspinningtop');
global.AvailableIndicators.push('bearishspinningtop');
global.AvailableIndicators.push('threeblackcrows');
global.AvailableIndicators.push('threewhitesoldiers');
module.exports = Indicators;
